<select class="inp pow_inp" name="pow" onChange='load_city(this.value);search_location("pow",this.value,kat_js)'>
	<option value="mazowieckie">Całe województwo</option>
	<option value="Warszawa">Warszawa</option>
	<option value="Radom">Radom</option>
	<option value="Płock">Płock</option>
	<option value="Siedlce">Siedlce</option>
	<option value="Ostrołęka">Ostrołęka</option>
	<option value="białobrzeski">pow. białobrzeski</option>
	<option value="ciechanowski">pow. ciechanowski</option>
	<option value="garwoliński">pow. garwoliński</option>
	<option value="gostyniński">pow. gostyniński</option>
	<option value="grodziski">pow. grodziski</option>
	<option value="grójecki">pow. grójecki</option>
	<option value="kozienicki">pow. kozienicki</option>
	<option value="legionowski">pow. legionowski</option>
	<option value="lipski">pow. lipski</option>
	<option value="łosicki">pow. łosicki</option>
	<option value="makowski">pow. makowski</option>
	<option value="miński">pow. miński</option>
	<option value="mławski">pow. mławski</option>
	<option value="nowodworski">pow. nowodworski</option>
	<option value="ostrołęcki">pow. ostrołęcki</option>
	<option value="ostrowski">pow. ostrowski</option>
	<option value="otwocki">pow. otwocki</option>
	<option value="piaseczyński">pow. piaseczyński</option>
	<option value="płoński">pow. płoński</option>
	<option value="pruszkowski">pow. pruszkowski</option>
	<option value="przasnyski">pow. przasnyski</option>
	<option value="przysuski">pow. przysuski</option>
	<option value="pułtuski">pow. pułtuski</option>
	<option value="radomski">pow. radomski</option>
	<option value="siedlecki">pow. siedlecki</option>
	<option value="sierpecki">pow. sierpecki</option>
	<option value="sochaczewski">pow. sochaczewski	</option>
	<option value="sokołowski">pow. sokołowski</option>
	<option value="szydłowiecki">pow. szydłowiecki</option>
	<option value="warszawski zachodni">pow. warszawski zachodni</option>
	<option value="węgrowski">pow. węgrowski</option>
	<option value="wołomiński">pow. wołomiński</option>
	<option value="wyszkowski">pow. wyszkowski</option>
	<option value="zwoleński">pow. zwoleński</option>
	<option value="żuromiński">pow. żuromiński</option>
	<option value="żyrardowski">pow. żyrardowski</option>
</select>