<select class="inp pow_inp" name="pow" onChange='load_city(this.value);search_location("pow",this.value,kat_js)'>
	<option value="śląskie">Całe województwo</option>
	<option value="Katowice">Katowice</option>
	<option value="Częstochowa">Częstochowa</option>
	<option value="Sosnowiec">Sosnowiec</option>
	<option value="Gliwice">Gliwice</option>
	<option value="Zabrze">Zabrze</option>
	<option value="Bielsko-Biała">Bielsko-Biała</option>
	<option value="Bytom">Bytom</option>
	<option value="Ruda Śląska">Ruda Śląska</option>
	<option value="Rybnik">Rybnik</option>
	<option value="Tychy">Tychy</option>
	<option value="Dąbrowa Górnicza">Dąbrowa Górnicza</option>
	<option value="Chorzów">Chorzów</option>
	<option value="Jaworzno">Jaworzno</option>
	<option value="Jastrzębie-Zdrój">Jastrzębie-Zdrój</option>
	<option value="Mysłowice">Mysłowice</option>
	<option value="Siemianowice Śląskie">Siemianowice Śląskie</option>
	<option value="Żory">Żory</option>
	<option value="Piekary Śląskie">Piekary Śląskie</option>
	<option value="Świętochłowice">Świętochłowice</option>
	<option value="będziński">pow. będziński</option>
	<option value="bielski">pow. bielski</option>
	<option value="bieruńsko-lędziński">pow. bieruńsko-lędziński</option>
	<option value="cieszyński">pow. cieszyński</option>
	<option value="częstochowski">pow. częstochowski</option>
	<option value="gliwicki">pow. gliwicki</option>
	<option value="kłobucki">pow. kłobucki</option>
	<option value="lubliniecki">pow. lubliniecki</option>
	<option value="mikołowski">pow. mikołowski</option>
	<option value="myszkowski">pow. myszkowski</option>
	<option value="pszczyński">pow. pszczyński</option>
	<option value="raciborski">pow. raciborski</option>
	<option value="rybnicki">pow. rybnicki</option>
	<option value="tarnogórski">pow. tarnogórski</option>
	<option value="wodzisławski">pow. wodzisławski</option>
	<option value="zawierciański">pow. zawierciański</option>
	<option value="żywiecki">pow. żywiecki</option>
</select>