<select class="inp pow_inp" name="pow" onChange='load_city(this.value);search_location("pow",this.value,kat_js)'>
	<option value="wielkopolskie">Całe województwo</option>
	<option value="Poznań">Poznań</option>
	<option value="Kalisz">Kalisz</option>
	<option value="Konin">Konin</option>
	<option value="Leszno">Leszno</option>
	<option value="chodzieski">pow. chodzieski</option>
	<option value="czarnkowsko-trzcianecki">pow. czarnkowsko-trzcianecki</option>
	<option value="gnieźnieński">pow. gnieźnieński</option>
	<option value="gostyński">pow. gostyński</option>
	<option value="grodziski">pow. grodziski</option>
	<option value="jarociński">pow. jarociński</option>
	<option value="kaliski">pow. kaliski</option>
	<option value="kępiński">pow. kępiński</option>
	<option value="kolski">pow. kolski</option>
	<option value="koniński">pow. koniński</option>
	<option value="kościański">pow. kościański</option>
	<option value="krotoszyński">pow. krotoszyński</option>
	<option value="leszczyński">pow. leszczyński</option>
	<option value="międzychodzki">pow. międzychodzki</option>
	<option value="nowotomyski">pow. nowotomyski</option>
	<option value="obornicki">pow. obornicki</option>
	<option value="ostrowski">pow. ostrowski</option>
	<option value="ostrzeszowski">pow. ostrzeszowski</option>
	<option value="pilski">pow. pilski</option>
	<option value="pleszewski">pow. pleszewski</option>
	<option value="poznański">pow. poznański</option>
	<option value="rawicki">pow. rawicki</option>
	<option value="słupecki">pow. słupecki</option>
	<option value="szamotulski">pow. szamotulski</option>
	<option value="średzki">pow. średzki</option>
	<option value="śremski">pow. śremski</option>
	<option value="turecki">pow. turecki</option>
	<option value="wągrowiecki">pow. wągrowiecki</option>
	<option value="wolsztyński">pow. wolsztyński</option>
	<option value="wrzesiński">pow. wrzesiński</option>
	<option value="złotowski">pow. złotowski</option>
</select>